name: Package DisableBlizzardCastBar

on:
  push:
    tags:
      - "*"
    paths-ignore:
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DisableBlizzardCastBar
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package and upload DisableBlizzardCastBar
        uses: BigWigsMods/packager@master
        with:
          args: -p 1102964 -a qKQxQ16x
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
